# Generated by Django 3.0.3 on 2020-02-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='member',
            field=models.IntegerField(max_length=2000, null=True),
        ),
    ]
